name: Update Submodules

# Run this workflow every time code is pushed to any branch
on: 
  push:
    branches:
      - '**'   # This runs on any branch

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Ensure submodules are checked out

    # Run the submodule update command
    - name: Update submodules
      run: git submodule update --remote

    # Commit updated submodules (if any)
    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet || git commit -m "CI: Update submodules"   # Check if there are any changes before committing

    # Pull the latest changes before pushing to avoid conflicts
    - name: Pull the latest changes
      run: git pull origin main --rebase

    # Push changes back to the repository using PAT
    - name: Push changes
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD
