name: Update Submodules

on:
  push:
    branches:
      - '**'   # This runs on any branch

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Ensure submodules are checked out

    # Check if the submodule is already up-to-date
    - name: Check submodule status
      id: submodule-status
      run: |
        # Get the current submodule commit hash
        CURRENT_COMMIT=$(git submodule status --recursive | awk '{ print $1 }')
        
        # Update submodule to the latest commit if it's not up to date
        git submodule update --remote --merge
        
        # Get the latest submodule commit hash after the update
        LATEST_COMMIT=$(git submodule status --recursive | awk '{ print $1 }')

        # Compare the commit hashes to check if update is needed
        if [ "$CURRENT_COMMIT" != "$LATEST_COMMIT" ]; then
          echo "Submodule updated."
          echo "submodule_updated=true" >> $GITHUB_ENV
        else
          echo "No submodule update needed."
          echo "submodule_updated=false" >> $GITHUB_ENV
        fi

    # Commit changes only if submodules were updated
    - name: Commit changes
      if: env.submodule_updated == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "CI: Update submodules" || echo "No changes to commit"

    # Pull the latest changes from the remote branch before pushing
    - name: Pull the latest changes
      if: env.submodule_updated == 'true'
      run: git pull origin main --rebase

    # Push the changes to the repository using the PAT
    - name: Push changes
      if: env.submodule_updated == 'true'
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD
