name: Update Submodules

# Run this workflow every time code is pushed to any branch
on: 
  push:
    branches:
      - '**'   # This runs on any branch

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Ensure submodules are checked out

    # Check if submodules are already up to date
    - name: Check for submodule updates
      id: submodule-check
      run: |
        # Save current submodule commit hash
        CURRENT_COMMIT=$(git submodule status | awk '{ print $1 }')
        # Fetch the latest changes for submodules
        git submodule update --remote
        # Get the latest submodule commit hash after update
        LATEST_COMMIT=$(git submodule status | awk '{ print $1 }')
        
        # Check if the submodule commit hash has changed
        if [ "$CURRENT_COMMIT" != "$LATEST_COMMIT" ]; then
          echo "Submodule has been updated."
          echo "updated=true" >> $GITHUB_ENV
        else
          echo "No submodule update needed."
          echo "updated=false" >> $GITHUB_ENV
        fi

    # Commit updated submodules (if any)
    - name: Commit changes
      if: env.updated == 'true'  # Only run this step if submodule was updated
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "CI: Update submodules"

    # Pull the latest changes from the remote main to prevent conflicts before pushing
    - name: Pull the latest changes
      if: env.updated == 'true'  # Only pull if submodule update occurred
      run: git pull origin main --rebase

    # Push changes back to the repository using PAT
    - name: Push changes
      if: env.updated == 'true'  # Only push if submodule was updated
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD
